#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace David_Hudgins_CPT_206_Lab4
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="stateInformation")]
	public partial class stateDataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public stateDataClassesDataContext() : 
				base(global::David_Hudgins_CPT_206_Lab4.Properties.Settings.Default.stateInformationConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public stateDataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public stateDataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public stateDataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public stateDataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<STATE> STATEs
		{
			get
			{
				return this.GetTable<STATE>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.STATE")]
	public partial class STATE
	{
		
		private string _POSTAL_CODE;
		
		private string _STATE_NAME;
		
		private string _CAPITAL;
		
		private string _POPULATION;
		
		private string _STATE_FLOWER;
		
		private string _STATE_BIRD;
		
		private string _STATE_COLORS;
		
		private string _FIRST_LARGEST_CITY;
		
		private string _SECOND_LARGEST_CITY;
		
		private string _THIRD_LARGEST_CITY;
		
		private string _MEDIAN_INCOME;
		
		private string _COMPUTER_JOBS;
		
		private string _FLAG_DESC;
		
		public STATE()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POSTAL_CODE", DbType="NVarChar(255)")]
		public string POSTAL_CODE
		{
			get
			{
				return this._POSTAL_CODE;
			}
			set
			{
				if ((this._POSTAL_CODE != value))
				{
					this._POSTAL_CODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATE_NAME", DbType="NVarChar(255)")]
		public string STATE_NAME
		{
			get
			{
				return this._STATE_NAME;
			}
			set
			{
				if ((this._STATE_NAME != value))
				{
					this._STATE_NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CAPITAL", DbType="NVarChar(255)")]
		public string CAPITAL
		{
			get
			{
				return this._CAPITAL;
			}
			set
			{
				if ((this._CAPITAL != value))
				{
					this._CAPITAL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POPULATION", DbType="NVarChar(255)")]
		public string POPULATION
		{
			get
			{
				return this._POPULATION;
			}
			set
			{
				if ((this._POPULATION != value))
				{
					this._POPULATION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATE_FLOWER", DbType="NVarChar(255)")]
		public string STATE_FLOWER
		{
			get
			{
				return this._STATE_FLOWER;
			}
			set
			{
				if ((this._STATE_FLOWER != value))
				{
					this._STATE_FLOWER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATE_BIRD", DbType="NVarChar(255)")]
		public string STATE_BIRD
		{
			get
			{
				return this._STATE_BIRD;
			}
			set
			{
				if ((this._STATE_BIRD != value))
				{
					this._STATE_BIRD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATE_COLORS", DbType="NVarChar(255)")]
		public string STATE_COLORS
		{
			get
			{
				return this._STATE_COLORS;
			}
			set
			{
				if ((this._STATE_COLORS != value))
				{
					this._STATE_COLORS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FIRST_LARGEST_CITY", DbType="NVarChar(255)")]
		public string FIRST_LARGEST_CITY
		{
			get
			{
				return this._FIRST_LARGEST_CITY;
			}
			set
			{
				if ((this._FIRST_LARGEST_CITY != value))
				{
					this._FIRST_LARGEST_CITY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SECOND_LARGEST_CITY", DbType="NVarChar(255)")]
		public string SECOND_LARGEST_CITY
		{
			get
			{
				return this._SECOND_LARGEST_CITY;
			}
			set
			{
				if ((this._SECOND_LARGEST_CITY != value))
				{
					this._SECOND_LARGEST_CITY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_THIRD_LARGEST_CITY", DbType="NVarChar(255)")]
		public string THIRD_LARGEST_CITY
		{
			get
			{
				return this._THIRD_LARGEST_CITY;
			}
			set
			{
				if ((this._THIRD_LARGEST_CITY != value))
				{
					this._THIRD_LARGEST_CITY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MEDIAN_INCOME", DbType="NVarChar(255)")]
		public string MEDIAN_INCOME
		{
			get
			{
				return this._MEDIAN_INCOME;
			}
			set
			{
				if ((this._MEDIAN_INCOME != value))
				{
					this._MEDIAN_INCOME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="COMPUTER_JOBS", Storage="_COMPUTER_JOBS", DbType="NVarChar(255)")]
		public string TECH_JOBS
		{
			get
			{
				return this._COMPUTER_JOBS;
			}
			set
			{
				if ((this._COMPUTER_JOBS != value))
				{
					this._COMPUTER_JOBS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FLAG_DESC", DbType="NVarChar(255)")]
		public string FLAG_DESC
		{
			get
			{
				return this._FLAG_DESC;
			}
			set
			{
				if ((this._FLAG_DESC != value))
				{
					this._FLAG_DESC = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
